=== richnou/odfi-doc/sw/core/src/main/java/org/odfi/collaboration/docbook/core/stylesheets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.idyria.com/osi/docbook/stylesheets"
	xmlns:tns="http://www.idyria.com/osi/docbook/stylesheets" elementFormDefault="qualified">
	
	<element name="Stylesheets">
		<complexType>
			<sequence>
				<element name="Description" type="string" minOccurs="0"></element>
				<element ref="tns:Stylesheet" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
			<attribute name="id" type="string" use="required"></attribute>
		</complexType>
	</element>
	
	
	<element name="Stylesheet">
		<complexType>
			<sequence>
				<element name="Description" type="string" minOccurs="0"></element>
				<element name="Output" type="tns:OutputType"></element>
				<element name="PostProcessing" type="tns:PostProcessingType"></element>
				<element name="TransformChain" type="tns:TransformChainType"></element>
			</sequence>
			<attribute name="name" type="string" use="required">
				<annotation>
					<documentation>
						The name of the stylesheet. If not provided the file name provided in path will be used
					</documentation>
				</annotation>
			</attribute>
		</complexType>
	</element>
	
	<complexType name="TransformChainType">
		<annotation>
			<documentation>
				A list of stylesheets to apply one after another
			</documentation>
		</annotation>	
		<sequence>
			<element name="Stylesheet" type="string" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	
	<complexType name="OutputType">
		<annotation>
			<documentation>
				Output configuration for a stylesheet
			</documentation>
		</annotation>		
		<sequence>
			<element name="Path" type="string" minOccurs="0">
				<annotation>
					<documentation>
						The path to which the results are to be outputed. This can be overriten when writing transformations results
						ex: 
						empty or ./ = Local folder
						output		= ./output/
						
					</documentation>
				</annotation>
			</element>
			<element name="File" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>
						Every File/Folder provided should be copied with the output to allow a good rendering.
						This is useful for HTML output if we need some additional stylesheets or Scripts
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	
	<complexType name="PostProcessingType">
		<sequence>
			<element name="Command" type="string" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>
						A List of commands to execute after the stylesheet transformation has happened
						Variables that can be put on command description:
						
						
						$repositoryPath$        : The folder in which the stylesheets.xml is located
						$stylesheetFolderPath$  : The folder in which the stylesheets main XSL file is located
						$outputFile$			: Path to the file outputed
						$outputFileFolder$		: Path to the file outputed Folder
						$outputFileName$		: Name of the file to be outputed, without extension
						
					</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	
</schema>

=== richnou/odfi-doc/cag-stylesheets/stylesheets.xml
<?xml version="1.0" encoding="UTF-8"?>
<Stylesheets id="uni.hd.cag" xmlns="http://www.idyria.com/osi/docbook/stylesheets" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.idyria.com/osi/docbook/stylesheets ../docbook/src/main/java/uni/hd/cag/eclipse/tools/docbook/stylesheets/stylesheets.xsd ">
  <Description>Stylesheets from CAG</Description>
  <Stylesheet path="./spec-xsl/html/spec-root.xsl" name="specification-html">
    <Description>Description</Description>
    <Output>
    	<Path>html</Path>
    	<File>css/spec-default.css</File>
    	<File>js/</File>
    </Output>
  </Stylesheet>
</Stylesheets>

=== richnou/odfi-doc/stylesheets/stylesheets.xml
<?xml version="1.0" encoding="UTF-8"?>
<Stylesheets id="uni.hd.cag"
	xmlns="http://www.idyria.com/osi/docbook/stylesheets" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.idyria.com/osi/docbook/stylesheets ../docbook/src/main/java/uni/hd/cag/eclipse/tools/docbook/stylesheets/stylesheets.xsd ">
	<Description>Stylesheets from CAG</Description>
	<Stylesheet name="specification-html">
		<Description>Description</Description>
		<TransformChain>
			<Stylesheet>./spec-xsl/html/spec-root.xsl</Stylesheet>
		</TransformChain>
		<Output>
			<Path>html</Path>
			<File>css/spec-default.css</File>
			<File>js/</File>
		</Output>
	</Stylesheet>
	<Stylesheet name="specification-pdf">
		<Description>Description</Description>
		<TransformChain>
			<Stylesheet>./spec-xsl/common/spec-validation.xsl</Stylesheet>
			<Stylesheet>./spec-xsl/xsl-fo/spec-root-fo.xsl</Stylesheet>
		</TransformChain>
		<Output>
			<Path>pdf</Path>
			<File>fop.xconf</File>
			<File>log4j.xml</File>
		</Output>
		<PostProcessing>
			<Command>$repositoryPath$/../external/apache-fop/transformToPDF $outputFile$ $outputFileFolder$ $outputFileName$.pdf</Command>
		</PostProcessing>
	</Stylesheet>
	<Stylesheet name="validation-tcl">
		<Description>Generate TCL code from a validation process</Description>
		<TransformChain>
			<Stylesheet>./validation/validation-tcl.xsl</Stylesheet>
		</TransformChain>
		<Output>
			<Path>validation-tcl</Path>
		</Output>
	</Stylesheet>
</Stylesheets>
